### ISSUE TITLE
Music not working

### ISSUE THREAD

**Issue by VioPaige** [MoolahModding/site#6]
I followed the tutorial of changing the ingame phone background in order to get a little familiar with the modding system for pd3.. however I have run into quite an issue. Whenever I insert my generated pak file into .../Content/Paks/~mods, all music and voicelines disappear (some sound effects still work), is there any reason why this could be occuring and any way to patch it?

**Comment by florensie** [comment]
I don't think this is a problem with the documentation. For general modding questions and help the [Moolah](https://discord.gg/VTe6pVYjWR) or [ModWorkShop](https://discord.gg/Eear4JW) discord is probably a better place. 😉
